library(RCurl)
library(XML)
library(stringr)
library(dplyr)

html <- readLines('data/alice.txt')
html <- htmlParse(html, asText=T)
doc <- xpathSApply(html, '//p', xmlValue)
library(tm)
library(SnowballC)
doc <- Corpus(VectorSource(doc))
inspect(doc)

doc <- tm_map(doc, content_transformer(tolower))       
doc <- tm_map(doc, removeNumbers)                       
doc <- tm_map(doc, removeWords, stopwords('english'))  
stop_words <- c(stopwords('en'), 'said')
doc <- tm_map(doc, removePunctuation)                   
doc <- tm_map(doc, stripWhitespace)  
dtm <- DocumentTermMatrix(doc)
dim(dtm)
inspect(dtm)
library(wordcloud)

typeof(dtm)
m <- as.matrix(dtm)
v <- sort(colSums(m), decreasing = T)
v[1:10]
df <- data.frame(word=names(v), freq=v)
head(df)
library(wordcloud2)
library(htmlwidgets)
library(htmltools)
library(jsonlite)
library(yaml)
library(base64enc)
library(devtools)

setwd("C:/workspace/r/data")
wordcloud2(df)
d200 <- df[1:200,]
wordcloud2(d200, shape='star')
wordcloud2(d200, minRotation = pi/6, maxRotation = pi/3, rotateRatio = 1.0)
wordcloud2(d200, size=0.5, col="random-light", backgroundColor="black")
wordcloud2(d200, figPath="Alicemask.png")
